module.exports = {
  PHASE_TYPES: ['TRIAL', 'INSTALLMENTS', 'RECURRING'],
  PRICING_MODES: ['FLAT', 'TIERED'],
  TIER_METRICS: ['TRANSACTION_COUNT', 'SALES_VALUE'],
  SUBSCRIPTION_STATUSES: ['TRIALING', 'ACTIVE', 'PAST_DUE', 'SUSPENDED', 'CANCELLED'],
  INVOICE_STATUSES: ['PENDING', 'PARTIAL', 'PAID', 'VOID'],
  INVOICE_KINDS: ['INSTALLMENT', 'RECURRING', 'ONE_OFF'],
  PAYMENT_METHODS: ['STK', 'MPESA_MANUAL', 'CASH', 'BANK', 'OTHER'],
  PAYMENT_STATUSES: ['PENDING', 'SUBMITTED', 'SUCCESS', 'FAILED', 'REJECTED', 'CANCELLED'],
  // Keeps the existing Business.subscriptionStatus field (used by the admin lists) in sync.
  BUSINESS_STATUS_MAP: { TRIALING: 'trialing', ACTIVE: 'active', PAST_DUE: 'past_due', SUSPENDED: 'suspended', CANCELLED: 'cancelled' },
  LIMITS: {
    STK_MIN_CENTS: 100,
    STK_MAX_CENTS: 15000000, // KES 150,000 (M-PESA STK ceiling)
    MANUAL_MAX_CENTS: 100000000,
    MAX_PENDING_MANUAL: 5,
    STK_TIMEOUT_MS: 90 * 1000,
    LATE_SUCCESS_WINDOW_MS: 24 * 3600 * 1000,
  },
};