const NOTIFICATION_TYPES = [
  'LOW_STOCK', 'OUT_OF_STOCK', 'PAYMENT_FAILED', 'REFUND_REQUEST', 'REFUND_COMPLETED',
  'CASH_SHORTAGE', 'CASH_OVER', 'SHIFT_OPENED', 'SHIFT_CLOSED',
  'SALE_CANCELLED', 'TRANSFER_REQUESTED', 'ETIMS_FAILED', 'CREDIT_DUE', 'CREDIT_SALE',
  'CUSTOMER_PAYMENT', 'SYSTEM_ALERT', 'EMPLOYEE_ALERT',
  // Support tickets (new)
  'TICKET_CREATED', 'TICKET_REPLY', 'TICKET_UPDATED', 'TICKET_RESOLVED', 'TICKET_CLOSED',
];

const SEVERITY = { INFO: 'info', WARNING: 'warning', CRITICAL: 'critical' };

const TYPE_SEVERITY = {
  LOW_STOCK: SEVERITY.WARNING,
  OUT_OF_STOCK: SEVERITY.CRITICAL,
  PAYMENT_FAILED: SEVERITY.CRITICAL,
  REFUND_REQUEST: SEVERITY.WARNING,
  REFUND_COMPLETED: SEVERITY.INFO,
  CASH_SHORTAGE: SEVERITY.CRITICAL,
  CASH_OVER: SEVERITY.WARNING,
  SHIFT_OPENED: SEVERITY.INFO,
  SHIFT_CLOSED: SEVERITY.INFO,
  SALE_CANCELLED: SEVERITY.WARNING,
  TRANSFER_REQUESTED: SEVERITY.INFO,
  ETIMS_FAILED: SEVERITY.CRITICAL,
  CREDIT_DUE: SEVERITY.WARNING,
  CREDIT_SALE: SEVERITY.INFO,
  CUSTOMER_PAYMENT: SEVERITY.INFO,
  SYSTEM_ALERT: SEVERITY.WARNING,
  EMPLOYEE_ALERT: SEVERITY.WARNING,
  TICKET_CREATED: SEVERITY.INFO,
  TICKET_REPLY: SEVERITY.INFO,
  TICKET_UPDATED: SEVERITY.INFO,
  TICKET_RESOLVED: SEVERITY.INFO,
  TICKET_CLOSED: SEVERITY.INFO,
};

const EMPLOYEE_RAISABLE_TYPES = [
  'LOW_STOCK', 'OUT_OF_STOCK', 'PAYMENT_FAILED', 'REFUND_REQUEST',
  'CASH_SHORTAGE', 'CREDIT_DUE', 'SYSTEM_ALERT',
];

const CREDIT_WARNING_THRESHOLD = 0.8;

module.exports = { NOTIFICATION_TYPES, SEVERITY, TYPE_SEVERITY, EMPLOYEE_RAISABLE_TYPES, CREDIT_WARNING_THRESHOLD };
