const NOTIFICATION_TYPES = [
  'LOW_STOCK', 'OUT_OF_STOCK', 'PAYMENT_FAILED', 'REFUND_REQUEST', 'REFUND_COMPLETED',
  'CASH_SHORTAGE', 'CASH_OVER', 'SHIFT_OPENED', 'SHIFT_CLOSED',
  'SALE_CANCELLED', 'TRANSFER_REQUESTED', 'ETIMS_FAILED', 'CREDIT_DUE',
  'SYSTEM_ALERT', 'EMPLOYEE_ALERT',
];

const SEVERITY = { INFO: 'info', WARNING: 'warning', CRITICAL: 'critical' };

// Default severity per type - drives badge colour / sound on the frontend.
const TYPE_SEVERITY = {
  LOW_STOCK: SEVERITY.WARNING,
  OUT_OF_STOCK: SEVERITY.CRITICAL,
  PAYMENT_FAILED: SEVERITY.CRITICAL,
  REFUND_REQUEST: SEVERITY.WARNING,
  REFUND_COMPLETED: SEVERITY.INFO,
  CASH_SHORTAGE: SEVERITY.CRITICAL,
  CASH_OVER: SEVERITY.WARNING,
  SHIFT_OPENED: SEVERITY.INFO,
  SHIFT_CLOSED: SEVERITY.INFO,
  SALE_CANCELLED: SEVERITY.WARNING,
  TRANSFER_REQUESTED: SEVERITY.INFO,
  ETIMS_FAILED: SEVERITY.CRITICAL,
  CREDIT_DUE: SEVERITY.WARNING,
  SYSTEM_ALERT: SEVERITY.WARNING,
  EMPLOYEE_ALERT: SEVERITY.WARNING,
};

// Subset a staff member (without notifications.manage) can raise manually
// against their own business. Deliberately excludes SHIFT_*, ETIMS_FAILED,
// TRANSFER_REQUESTED, SALE_CANCELLED and REFUND_COMPLETED - those are
// always system-generated, never hand-typed, so a cashier can't fabricate
// "the transfer auto-fired" or "the refund was already completed".
const EMPLOYEE_RAISABLE_TYPES = [
  'LOW_STOCK', 'OUT_OF_STOCK', 'PAYMENT_FAILED', 'REFUND_REQUEST',
  'CASH_SHORTAGE', 'CREDIT_DUE', 'SYSTEM_ALERT',
];

const CREDIT_WARNING_THRESHOLD = 0.8; // 80% of creditLimit - fires a CREDIT_DUE warning

module.exports = { NOTIFICATION_TYPES, SEVERITY, TYPE_SEVERITY, EMPLOYEE_RAISABLE_TYPES, CREDIT_WARNING_THRESHOLD };