const TICKET_STATUSES = ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'];
const TICKET_PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];
const TICKET_CATEGORIES = ['SALES', 'PAYMENTS', 'INVENTORY', 'PRODUCTS', 'REPORTS', 'PRINTING', 'LOGIN', 'ETIMS', 'OTHER'];

module.exports = { TICKET_STATUSES, TICKET_PRIORITIES, TICKET_CATEGORIES };
